---
title: "Integrating proteomics data"
author: "Pratheepa Jeganathan, Susan Holmes"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  BiocStyle::html_document
params:
  K: 5
  R: 100
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 20,
  fig.height = 15)
```

```{r read_arg}
K <- params$K
K
iter <- params$R
iter
```

```{r}
#library(flowCore)
library(SingleCellExperiment)
library(ggplot2)
library(rstan)
#library(scater)
library(plyr)
library(reshape2)
library(readr)
#library(CATALYST)
library(magrittr)
#library(scMerge)
# library(MultiAssayExperiment)
library(dplyr)
library(DESeq2)
library(abind)
library(tibble)
library(RColorBrewer)

# library(igraph)
# library(raster)
# library(spdep)
# library(stars)
library(stringr)
library(ggthemes)

library(pheatmap)



# library(uwot)# UMAP
# library(scattermore)# to visualize more points
# library(ggthemes)# colors
# 
# library(gstat)# variogram
# library(sp)
```

# Topic modeling

```{r}
id <- 3
mibi_sample_id <- readRDS(paste0("../Results/mibi_sample_id_", id, ".rds"))
# consider tumor and machrophage cells
mibi_sample_id <- mibi_sample_id[, mibi_sample_id$cell_type %in% c("Macrophages", "Tumor")]
mibi_sample_id
```


```{r}
# cell size normalized, asinh, standardized across the markers
# we couldn't guess the protein marker mean and standard deviation. We will 

rw_mins <- rowMins(assay(mibi_sample_id))*(-1)
assay(mibi_sample_id) <-  assay(mibi_sample_id) + rw_mins
assay(mibi_sample_id) <- sinh(assay(mibi_sample_id))
assay(mibi_sample_id) <- t(t(assay(mibi_sample_id)) * mibi_sample_id$cellSize)
x <- assay(mibi_sample_id) %>% t()
x <- apply(x , c(1,2), function(y){as.integer(y)})
x <- as.matrix(x)
```

```{r}
# theta[d] ~ dirichlet(alpha), alpha pseudocount for each topic
# beta[k] ~ dirichlet(gamma), gamma pseudocount for each ASV in each topic
stan.data <- list(K = K, 
  V = ncol(x), 
  D = nrow(x), 
  n = x, 
  alpha = rep(.8, K), 
  gamma = rep(.5, ncol(x))
)
```

```{r}
fileN <- paste0("../Results/LDA_id_",id,"_K_",K,"_ite_",iter,".RData")
fileN
```

```{r}
t1 <- proc.time()
stan.fit <- stan(file = "./lda.stan", 
  data = stan.data, 
  iter = iter, 
  chains = 4, 
  sample_file = NULL,
  diagnostic_file = NULL,
  cores = 4,
  control = list(adapt_delta = 0.9),
  save_dso = TRUE,
  algorithm = "NUTS")
proc.time() - t1

save(stan.fit, file = fileN)
```

```{r}
load(file = fileN)
```

Sampler diagnostics
```{r}
sampler_params <- get_sampler_params(stan.fit, inc_warmup = FALSE)
colnames(sampler_params[[1]])

mean_accept_stat_by_chain <- sapply(sampler_params, function(x) mean(x[, "accept_stat__"]))
mean_accept_stat_by_chain

max_treedepth_by_chain <- sapply(sampler_params, function(x) max(x[, "treedepth__"]))
max_treedepth_by_chain
```


# Visualization 

## Extract posterior samples
```{r}
samples <- rstan::extract(stan.fit, 
                          permuted = TRUE, 
                          inc_warmup = FALSE, 
                          include = TRUE)# samples is a list
```

## Alignment
- Create a Topic $*$ Chain matrix
```{r}
source("../R_BANF/alignmentMatrix.R")
source("../R_BANF/thetaAligned.R")
theta <- samples$theta 
aligned <- alignmentMatrix(theta, 
                           mibi_sample_id, 
                           K, 
                           iter = iter, 
                           chain = 4)
theta_aligned <- thetaAligned(theta, 
                              K, 
                              aligned, 
                              iter = iter, 
                              chain = 4)
dimnames(theta_aligned)[[2]] <- colnames(mibi_sample_id)
dimnames(theta_aligned)[[3]] <- c(paste0("Topic_", seq(1,K)))

# array to a dataframe
theta_all <- melt(theta_aligned)
colnames(theta_all) <- c("iteration", "Sample", "Topic", "topic.dis")
theta_all$Chain <- paste0("Chain ", rep(seq(1, 4), each = (iter/2)))

sam <- colData(mibi_sample_id) %>% data.frame()
theta_all$Sample <- as.character(theta_all$Sample)
theta_all <- left_join(theta_all, sam, by =c("Sample"= "cell_id"))
theta_all$Chain <- factor(theta_all$Chain)
theta_all$Topic <- factor(theta_all$Topic)
theta_all$Sample <- factor(theta_all$Sample)

theta_all$cell_type <- factor(theta_all$cell_type)
```

```{r}
manual_col <- tableau_color_pal("Classic 20")(length(unique(theta_all$cell_type)))

theta_summary <- theta_all %>% 
  group_by(Sample, Topic, cell_type) %>% 
  summarize(median.topic.dis = median(topic.dis)) %>% 
  ungroup() %>% 
  mutate(Topic = factor(Topic, levels = rev(str_c("Topic_",1:K))))

theta_summary <- dplyr::filter(theta_summary, cell_type %in% c("Macrophages", "Tumor"))

sample_cells <- unique(theta_summary$Sample)
sample_cells_select <- sample(sample_cells, 50)

theta_summary <- dplyr::filter(theta_summary, Sample %in% sample_cells_select)

p <- ggplot(theta_summary, 
           aes(x = cell_type, 
               y = Topic, 
               fill = cell_type))
p <- p+
  geom_tile(aes(alpha = median.topic.dis))+
  facet_grid(.~Sample, scale = "free")+
  xlab("Cell type") +
  scale_fill_manual(name = "Cell type", 
                    values = c("steelblue1","green3")) +
  scale_alpha(name = "median topic distribution") +
  theme_minimal(base_size = 20) +  
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text.x = element_text(angle = 90), 
        axis.text.x=element_blank()) 
p

ggsave(paste0("../Figures/topic_dis_id_",id,"_K_",K, ".png"), p, width = 20, height = 6)
```


## Marker distribution
```{r}
source("../R_BANF/betaAligned.R")
beta <- samples$beta # an array (iterations *topic * marker)
beta_aligned <- betaAligned(beta, 
                            K, 
                            aligned, 
                            iter = iter, 
                            chain = 4) # an array (iterations *topic * ASV)

# array to data frame
beta_hat <- beta_aligned %>%
  melt(varnames = c("iterations", "topic", "marker_ix"), 
       value.name = "beta_h") %>% as_tibble()
beta_hat$marker <- colnames(x)[beta_hat$marker_ix]


# join rowData with beta_hat
marker_info <- rowData(mibi_sample_id) %>% data.frame()
marker_info$marker <- rownames(marker_info)

beta_hat <- beta_hat %>%
  left_join(marker_info, by = "marker") %>% mutate(topic = paste("Topic", topic))


beta_hat$marker <- factor(beta_hat$marker)
beta_hat$marker_ix <- factor(beta_hat$marker_ix)
beta_hat$topic <- factor(beta_hat$topic)


beta_summary <- beta_hat %>% 
  dplyr::group_by(marker_ix, topic) %>% 
  dplyr::summarise(
    marker = marker[1],
    beta_median = median(beta_h),
    marker = marker[1],
    hgnc_symbol = hgnc_symbol[1]
  )

beta_subset <- beta_summary
beta_subset$marker_ix <- rep(seq_len(nrow(beta_subset) / K), each = K)

```


```{r}
beta_subset <- beta_subset %>% 
  arrange(marker_ix, topic)

beta_subset <- beta_subset %>%
  mutate(Class = factor(marker, levels = unique(beta_subset$marker)),
         Topic = str_remove(topic, "Topic "))


beta_subset$Topic <- factor(beta_subset$Topic, levels = seq(1,K) %>% as.character())

p <- ggplot(beta_subset, 
            aes(x = Topic, 
                y = marker, 
                fill = beta_median)) +
  geom_tile() +
  ylab("Marker")+
  scale_fill_gradientn(name = "Median ASV distribution", 
                       colours = c("gray98", "dodgerblue"), 
                       trans = "log10") +  
  theme_minimal(base_size = 20) +
  theme(plot.title = element_text(hjust = 0.5)) 

p
ggsave(paste0("../Figures/asv_dist_barplot_id_",id, "_K_",K, ".png"), p, width = 13, height = 11)
```
